# Generated by Django 3.2.9 on 2021-12-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
