# Generated by Django 3.2.9 on 2021-12-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0002_employee_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
